pipeline {
    agent any

    tools {
        nodejs 'node18'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Manish0085/Videly.git',
                    credentialsId: 'github-pat'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Stream-frontend/frontend') {
                    sh '''
                    node -v
                    npm -v
                    npm install
                    '''
                }
            }
        }

        stage('Build Project') {
            steps {
                dir('Stream-frontend/frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('Stream-frontend/frontend') {
                    sh '''
                    sudo rm -rf /var/www/html/*
                    sudo cp -r dist/* /var/www/html/
                    sudo systemctl reload nginx
                    '''
                }
            }
        }
    }

    post {
        success {
            echo '🎉 Deployment Successful!'
        }
    }
}
